version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: posthog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: clickhouse123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  posthog:
    image: posthog/posthog:latest
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/posthog
      POSTGRES_HOST: postgres
      POSTGRES_DB: posthog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
      SECRET_KEY: your-secret-key-here-change-this-in-production
      SITE_URL: http://localhost:8000
      DISABLE_SECURE_SSL_REDIRECT: "true"
      DISABLE_EMAIL_VERIFICATION: "true"
      PRIMARY_DB: postgres
      CLICKHOUSE_DISABLE_EXTERNAL_SCHEMAS: "false"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_DATABASE: "default"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: "clickhouse123"
      CLICKHOUSE_SECURE: "false"
      CLICKHOUSE_VERIFY: "false"
      PRIMARY_DB: postgres
      MULTI_TENANCY: "false"
    ports:
      - "8000:8000"
    volumes:
      - posthog_data:/var/lib/posthog
    restart: unless-stopped

volumes:
  postgres_data:
  posthog_data:
  clickhouse_data: 